export enum ModelLimit {
  free = "FREE",
  standard = "STANDARD",
  premium = "PREMIUM",
}

export enum ModelName {
  gpt_4_1 = "gpt-4.1",
  DeepSeek_R1_0528 = "DeepSeek-R1-0528",
  gpt_4o_transcribe = "gpt-4o-transcribe",
  grok_3 = "grok-3",
  Sora = "Sora",
  grok_3_mini = "grok-3-mini",
  gpt_o4_mini = "gpt-o4-mini",
  gpt_o4_mini_tts = "gpt-o4-mini-tts",
  DeepSeek_R1 = "DeepSeek-R1",
  model_router = "model-router",
  o1 = "o1",
  gpt_4o = "gpt-4o",
}

export const AI_MODELS = [
  {
    name: "Model Router",
    value: "model-router",
    available: true,
    limit: ModelLimit.standard,
    logo: "/images/models/microsoft.svg",
    type: "Chat completion",
    cross: true,
  },
  {
    name: "GPT 4.1",
    value: "gpt-4.1",
    available: true,
    limit: ModelLimit.standard,
    logo: "/images/models/openai.svg",
    type: "Chat completion",
    cross: true,
  },
  {
    name: "DeepSeek R1-0528",
    value: "DeepSeek-R1-0528",
    available: true,
    limit: ModelLimit.standard,
    logo: "/images/models/deepseek.svg",
    type: "Chat completion",
    cross: true,
  },
  {
    name: "Grok 3",
    value: "grok-3",
    available: true,
    limit: ModelLimit.standard,
    logo: "/images/models/grok.svg",
    type: "Chat completion",
    cross: true,
  },
  {
    name: "GPT o1", // => not supporting temperature
    value: "o1",
    available: true, // should be true
    limit: ModelLimit.standard,
    logo: "/images/models/openai.svg",
    type: "Chat completion",
    cross: true,
  },
  {
    name: "GPT o4-mini", // => not supporting temperature
    value: "gpt-o4-mini",
    available: true, // should be true
    limit: ModelLimit.standard,
    logo: "/images/models/openai.svg",
    type: "Chat completion",
    cross: true,
  },
  {
    name: "GPT o4",
    value: "gpt-o4",
    available: true,
    limit: ModelLimit.standard,
    logo: "/images/models/openai.svg",
    type: "Chat completion",
    cross: true,
  },
  {
    name: "gpt-4o-transcribe",
    value: "gpt-4o-transcribe",
    available: false,
    limit: ModelLimit.standard,
    logo: "/images/models/openai.svg",
    type: "Speech to text",
  },
  {
    name: "Sora",
    value: "sora",
    available: false,
    limit: ModelLimit.standard,
    logo: "/images/models/openai.svg",
    type: "Video generation",
  },
  {
    name: "grok-3-mini",
    value: "grok-3-mini",
    available: false,
    limit: ModelLimit.standard,
    logo: "/images/models/grok.svg",
    type: "Chat completion",
  },
  {
    name: "gpt-o4-mini-tts",
    value: "gpt-o4-mini-tss",
    available: false,
    limit: ModelLimit.standard,
    logo: "/images/models/openai.svg",
    type: "Text to speech",
  },
  {
    name: "DeepSeek-R1",
    value: "deepseek-r1",
    available: false,
    limit: ModelLimit.standard,
    logo: "/images/models/deepseek.svg",
    type: "Chat completion",
  },
];
